version: '3'
services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'mortgage_payments'
      MYSQL_PORT: web
      MYSQL_USER: web
      MYSQL_ROOT_PASSWORD: web
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
  web:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password123'

volumes:
  my-db: